// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/auction/v1/auction.proto

package auctionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionRequest) Reset() {
	*x = GetAuctionRequest{}
	mi := &file_proto_auction_v1_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionRequest) ProtoMessage() {}

func (x *GetAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_v1_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_v1_auction_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuctionRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type GetAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId      string                 `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	StartPrice    int64                  `protobuf:"varint,3,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionResponse) Reset() {
	*x = GetAuctionResponse{}
	mi := &file_proto_auction_v1_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionResponse) ProtoMessage() {}

func (x *GetAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_v1_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_v1_auction_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuctionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAuctionResponse) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *GetAuctionResponse) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *GetAuctionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_auction_v1_auction_proto protoreflect.FileDescriptor

const file_proto_auction_v1_auction_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/auction/v1/auction.proto\x12\n" +
	"auction.v1\"2\n" +
	"\x11GetAuctionRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\"z\n" +
	"\x12GetAuctionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\tR\bsellerId\x12\x1f\n" +
	"\vstart_price\x18\x03 \x01(\x03R\n" +
	"startPrice\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2]\n" +
	"\x0eAuctionService\x12K\n" +
	"\n" +
	"GetAuction\x12\x1d.auction.v1.GetAuctionRequest\x1a\x1e.auction.v1.GetAuctionResponseBAZ?github.com/in-jun/go-structure-example/proto/auction/v1;auctionv1b\x06proto3"

var (
	file_proto_auction_v1_auction_proto_rawDescOnce sync.Once
	file_proto_auction_v1_auction_proto_rawDescData []byte
)

func file_proto_auction_v1_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_v1_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_v1_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_v1_auction_proto_rawDesc), len(file_proto_auction_v1_auction_proto_rawDesc)))
	})
	return file_proto_auction_v1_auction_proto_rawDescData
}

var file_proto_auction_v1_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_auction_v1_auction_proto_goTypes = []any{
	(*GetAuctionRequest)(nil),  // 0: auction.v1.GetAuctionRequest
	(*GetAuctionResponse)(nil), // 1: auction.v1.GetAuctionResponse
}
var file_proto_auction_v1_auction_proto_depIdxs = []int32{
	0, // 0: auction.v1.AuctionService.GetAuction:input_type -> auction.v1.GetAuctionRequest
	1, // 1: auction.v1.AuctionService.GetAuction:output_type -> auction.v1.GetAuctionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auction_v1_auction_proto_init() }
func file_proto_auction_v1_auction_proto_init() {
	if File_proto_auction_v1_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_v1_auction_proto_rawDesc), len(file_proto_auction_v1_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_v1_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_v1_auction_proto_depIdxs,
		MessageInfos:      file_proto_auction_v1_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_v1_auction_proto = out.File
	file_proto_auction_v1_auction_proto_goTypes = nil
	file_proto_auction_v1_auction_proto_depIdxs = nil
}
