version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - noctx
    - gosec
    - errname
    - errorlint
  settings:
    gosec:
      excludes:
        - G114
        - G108
        - G704
        - G117
  exclusions:
    rules:
      - linters:
          - errcheck
        path: "_test\\.go"
    paths:
      - vendor
      - proto
